//
//  .swiftlint.yml
//  GameCatalog
//
//  Created by Heri Sandiyadi on 09/07/25.
//

disabled_rules:
  - trailing_whitespace
  - line_length
  - force_cast

opt_in_rules:
  - empty_count
  - explicit_self

included:
  - GameCatalog

excluded:
  - Carthage
  - Pods
  - Build

reporter: xcode
