workflows:
  ios-project-debug:
    name: iOS Debug Build and Test
    environment:
      xcode: latest
      cocoapods: default
      vars:
        XCODE_PROJECT: "GameCatalog.xcodeproj" # Ganti jika Anda menggunakan .xcworkspace
        XCODE_SCHEME: "GameCatalog" # Pastikan scheme ini bisa dijalankan dan memiliki unit test target
        XCODE_DESTINATION: "platform=iOS Simulator,name=iPhone 16 Pro Max,OS=18.3.1"
    scripts:
      - name: Install dependencies
        script: |
          gem install cocoapods # opsional, jika belum terinstal
          pod install || true   # akan di-skip jika tidak pakai .xcworkspace

      - name: Run unit tests
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -destination "$XCODE_DESTINATION" \
            clean build test \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: Build debug app
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -destination "$XCODE_DESTINATION" \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
            build

    artifacts:
      - build/ios/Debug-iphonesimulator/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Logs/scan/*.log

    publishing:
      email:
        recipients:
          - herisandiyadi@gmail.com
        notify:
          success: true
          failure: true
